<?xml version="1.0" encoding="UTF-8"?><testrun name="JedisPools.jedisPool" project="Redis" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testcase name="jedisPool" classname="com.ithup.jedis.JedisPools" time="0.092">
    <error>redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool&#13;
	at redis.clients.util.Pool.getResource(Pool.java:50)&#13;
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:86)&#13;
	at com.ithup.tool.JedisPoolUtils.getJedis(JedisPoolUtils.java:46)&#13;
	at com.ithup.jedis.JedisPools.jedisPool(JedisPools.java:39)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.UnknownHostException: redis.url&#13;
	at redis.clients.jedis.Connection.connect(Connection.java:154)&#13;
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:83)&#13;
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1643)&#13;
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:85)&#13;
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:861)&#13;
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435)&#13;
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)&#13;
	at redis.clients.util.Pool.getResource(Pool.java:48)&#13;
	... 26 more&#13;
Caused by: java.net.UnknownHostException: redis.url&#13;
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)&#13;
	at java.net.PlainSocketImpl.connect(Unknown Source)&#13;
	at java.net.SocksSocketImpl.connect(Unknown Source)&#13;
	at java.net.Socket.connect(Unknown Source)&#13;
	at redis.clients.jedis.Connection.connect(Connection.java:148)&#13;
	... 33 more&#13;
&#13;
</error>
  </testcase>
</testrun>
