package day12;
/**
 * 异常处理
 * @author acer
 *
 */
public class ExceptionDemo01 {
	public static void fun() throws MyException{
		System.out.println("使用自定义类");
	}
	public static void main(String args[]){
		try {
			fun();
		} catch (MyException e) {
			e.printStackTrace();
		}
	}
}
